Added testSetName()
mlhaus/KCC-Java2-Thr-Night pull request #24
Opened 2020-10-22 23:59 UTC by Nwebber

2020-10-23 21:53 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        Animal instance = new Animal();
The setUp() call will instantiate the instance. You don't need this line.

2020-10-23 21:53 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        instance.setName(expected);
This line is good, but you need an assertEquals line after this one.

2020-10-23 21:54 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        Animal instance = new Animal();
Just use setUp();

2020-10-23 21:54 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        Animal instance = new Animal();
We don't need this line

2020-10-23 21:55 UTC, mlhaus commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        instance.setGender(expected);
You need an assertEquals or assertTrue statement after this.

2020-10-23 21:55 UTC, mlhaus requested changes
There's a few things to update here.

2020-10-29 23:32 UTC, cash12121 commented
Hey, @Nwebber it seems you added the UIUtility and Main framework to this Pull Request. It would be better if you were to revert those commits and create a new pull request. One way of doing this is when you have an Open Pull Request is to put your new changes for something separate in a different branch. Then creating a PR with that branch to merge into main. 

So like create a branch called ui-utility and commit those changes there. Then make a PR. 

This is so you can work on multiple pull requests to make changes if needed.

2020-10-29 23:45 UTC, Nwebber reviewed
This should be all the changes requested

2020-10-29 23:45 UTC, Nwebber commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        Animal instance = new Animal();
Alright, I have deleted the SetUp() line from here

2020-10-29 23:45 UTC, Nwebber commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        Animal instance = new Animal();
Should be Corrected

2020-10-29 23:45 UTC, Nwebber commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        instance.setName(expected);
Alright, corrected the problems (I think)

2020-10-29 23:45 UTC, Nwebber commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        Animal instance = new Animal();
Got it fixed, oddly enough, When i tried to have a capital M on male, the test failed because it expected a lowercase m

2020-10-29 23:45 UTC, Nwebber commented on src/test/java/edu/kcc/animal/AnimalTest.java
> +        instance.setGender(expected);
Got it added

2020-10-31 00:08 UTC, merged